name: Ourworld.tf
on: 
  push:
    branch: [ development ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www.ourworld.tf
      uses: appleboy/ssh-action@master
      with:
        host: www.ourworld.tf
        username: webuser
        key: ${{ secrets.TF_SECRET }}
        port: 34022
        script: |
          cd websites/www_ourworld_tf/
          git log -1
          git pull
          bash build.sh

          
