name: www2.ourworld.tf
on:
  push:
    branches: [ development ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www2.ourworld.tf
      uses: appleboy/ssh-action@master
      with:
        host: www2.ourworld.tf
        username: webuser
        key: ${{ secrets.TF_SECRET }}
        port: 34022
        script: |
          cd websites/www2/www_ourworld_tf/
          git log -1
          git fetch
          git reset --hard origin/development
          sed -i "s/https:\/\/www.ourworld.tf/https:\/\/www2.ourworld.tf/g" config.toml
          ./build.sh

  wait:
    needs: deploy
    name: Wait for Website Update
    runs-on: ubuntu-latest
    steps:
    - name: Wait Period
      id: wait-deploy
      run: |
        echo "Sleeping for 30"
        sleep 30
        
  checklinks:
    needs: wait
    name: Check for Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Check for Broken Links
        id: link-report
        uses: docker://ghcr.io/threefoldfoundation/website-link-checker:latest
        with:
          args: 'https://www2.ourworld.tf -w 404'